data :
  read :
    - cold_start_test 
    - consumption_train
    - meta
    - submission_format
    - submission_benchmark

copy-data-1:
  - from : submission_format
    to : submission

# fillna-by-mean-timestamp :
#   - data : cold_start_test
#     group-on :
#       - timestamp
#     target :
#       - temperature
#   - data : submission
#     group-on :
#       - timestamp
#     target :
#       - temperature
#     search-in : cold_start_test

ohe :
  - data : meta
    skip : 
      - series_id

customize-cells :
  - data : meta
    func : ohe_true_false

generate-column-0 :
  - data : cold_start_test
    func : get_week_from_timestamp
    in-col : timestamp
    out-col : week
  - data : cold_start_test
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : on_off
  - data : cold_start_test
    func : get_hour_from_timestamp
    in-col : timestamp
    out-col : hour
  - data : cold_start_test
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : day
  - data : consumption_train
    func : get_week_from_timestamp
    in-col : timestamp
    out-col : week
  - data : consumption_train
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : on_off
  - data : consumption_train
    func : get_hour_from_timestamp
    in-col : timestamp
    out-col : hour
  - data : consumption_train
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : day
  - data : submission
    func : get_week_from_timestamp
    in-col : timestamp
    out-col : week
  - data : submission
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : on_off
  - data : submission
    func : get_hour_from_timestamp
    in-col : timestamp
    out-col : hour
  - data : submission
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : day

merge:
  - left : cold_start_test
    right : meta
    how : left
    merge-on : series_id
  - left : consumption_train
    right : meta
    how : left
    merge-on : series_id
  - left : submission
    right : meta
    how : left
    merge-on : series_id

# Takes series as input
customize-row :
  - data : cold_start_test
    func : replace_day_with_off
  - data : consumption_train
    func : replace_day_with_off
  - data : submission
    func : replace_day_with_off

delete-columns :
  - data : cold_start_test
    columns:
      - monday_is_day_off
      - tuesday_is_day_off
      - wednesday_is_day_off
      - thursday_is_day_off
      - friday_is_day_off
      - saturday_is_day_off
      - sunday_is_day_off
  - data : consumption_train
    columns:
      - monday_is_day_off
      - tuesday_is_day_off
      - wednesday_is_day_off
      - thursday_is_day_off
      - friday_is_day_off
      - saturday_is_day_off
      - sunday_is_day_off
  - data : submission
    columns:
      - monday_is_day_off
      - tuesday_is_day_off
      - wednesday_is_day_off
      - thursday_is_day_off
      - friday_is_day_off
      - saturday_is_day_off
      - sunday_is_day_off
      # - prediction_window

cache : True

fillna :
  - data : cold_start_test
    value : 0
  - data : consumption_train
    value : 0
  - data : submission
    value : 0

csv-1 :
  data :
    - submission
    - cold_start_test
    - consumption_train
  index : false

# lstm :
#   train:
#     data : consumption_train
#     epoch : 3
#     output : consumption
#     save : 'lstm_hour_model'
#     input : [temperature,week,on_off,hour,day,surface_large,surface_medium,surface_small,surface_x-large,surface_x-small,surface_xx-large,surface_xx-small,base_temperature_high,base_temperature_low]
#     seq-on : series_id

# lstm-1 :
#   load : lstm_hour_model
#   train :
#     data : cold_start_test
#     output : consumption
#     input : [temperature,week,on_off,hour,day,surface_large,surface_medium,surface_small,surface_x-large,surface_x-small,surface_xx-large,surface_xx-small,base_temperature_high,base_temperature_low]
#     seq-on : series_id
#     epoch : 1
#     predict : submission

# cache : True

# transfer:
#   from :
#     data : submission_hr_pred
#     key : [pred_id]
#     col : consumption
#   to :
#     data : submission_benchmark
#     key : [pred_id]
#     col : consumption

# csv-2 :
#   data :
#     - submission_benchmark
#   index : false

