data :
  read :
    - cold_start_test :
      skip : [0]
    - consumption_train :
      skip : [0]
    - meta
    - submission_format

concat :
  data :
    target : cold_start_test
    dataframes :
      - consumption_train
      
delete-df:
  data :
    - consumption_train

normalize :
  data : cold_start_test
  group-on : series_id
  target : consumption 

# csv- :
#   index : false
#   data :
#     - cold_start_test_norm_factor
#     - cold_start_test

# fillna-by-mean:
#   - data : cold_start_test
#     over : timestamp
        
ohe :
  - data : meta
    skip : 
      - series_id

customize-cells :
  - data : meta
    func : ohe_true_false

copy-data-1:
  from : submission_format
  to : submission

# Takes array as input and return True against the values to delete and False for not to delete 
delete-rows-0 :
  - data : cold_start_test
    in-col : temperature
    condition : is_temp_na
  # - data : cold_start_test_temp_na
  #   in-col : temperature
  #   condition : is_temp_not_na
  - data : submission
    in-col : temperature
    condition : is_temp_na
  - data : submission
    in-col : prediction_window
    condition : weekly
  - data : submission
    in-col : prediction_window
    condition : daily

generate-column :
  - data : cold_start_test
    func : get_week_from_timestamp
    in-col : timestamp
    out-col : week
  # - data : cold_start_test
  #   func : get_day_from_timestamp
  #   in-col : timestamp
  #   out-col : day
  - data : cold_start_test
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : on_off
  - data : cold_start_test
    func : get_hour_from_timestamp
    in-col : timestamp
    out-col : hour
  # - data : submission
  #   func : get_day_from_timestamp
  #   in-col : timestamp
  #   out-col : day
  - data : submission
    func : get_week_from_timestamp
    in-col : timestamp
    out-col : week
  - data : submission
    func : get_day_from_timestamp
    in-col : timestamp
    out-col : on_off
  - data : submission
    func : get_hour_from_timestamp
    in-col : timestamp
    out-col : hour

cache : true

# delete-rows-1 :
#   - data : cold_start_test
#     in-col : hour
#     condition : day_time
#   - data : submission
#     in-col : hour
#     condition : day_time

merge:
  - left : cold_start_test
    right : meta
    how : left
    on : series_id
  - left : submission
    right : meta
    how : left
    on : series_id

# delete-rows-02 :
#   # - data : cold_start_test
#   #   in-col : surface_large
#   #   condition : is_one
#   - data : cold_start_test
#     in-col : surface_medium
#     condition : is_one
#   - data : cold_start_test
#     in-col : surface_small
#     condition : is_one
#   - data : cold_start_test
#     in-col : surface_x-large
#     condition : is_one
#   - data : cold_start_test
#     in-col : surface_x-small
#     condition : is_one
#   - data : cold_start_test
#     in-col : surface_xx-large
#     condition : is_one
#   - data : cold_start_test
#     in-col : surface_xx-small
#     condition : is_one

# Takes series as input
customize-row :
  - data : cold_start_test
    func : replace_day_with_off
  - data : submission
    func : replace_day_with_off

delete-columns :
  - data : cold_start_test
    columns:
      - monday_is_day_off
      - tuesday_is_day_off
      - wednesday_is_day_off
      - thursday_is_day_off
      - friday_is_day_off
      - saturday_is_day_off
      - sunday_is_day_off
  - data : submission
    columns:
      - monday_is_day_off
      - tuesday_is_day_off
      - wednesday_is_day_off
      - thursday_is_day_off
      - friday_is_day_off
      - saturday_is_day_off
      - sunday_is_day_off
      - prediction_window

delete-rows-2:
  - data : cold_start_test
    in-col : on_off
    condition : is_zero

group-by :
  - data : cold_start_test
    group-on :
      - series_id
      - week
      - hour
      - on_off
    as_index : False

display :
  - data : cold_start_test
    min : consumption
    max : consumption

csv-0 :
  index : false
  data :
    - cold_start_test

csv-1 :
  data :
    - meta

# keras:
#   train :
#     data : cold_start_test
#     skip : [series_id]
#     output : consumption
#     activation : softmax
#     model : sequential
#     initializer : normal
#     loss : mean_squared_error
#     optimizer : sgd
#     metrics : [accuracy]
#     validate : true
#     epochs : 20
#   predict :
#     data : submission

lightgbm :
  train :
    data : cold_start_test
    skip : [series_id, week, hour]
    output : consumption
    type : LGBMRegressor
  predict :
    data : submission

# xgboost :
#   pre-train:
#     data : cold_start_test_temp_na
#     skip : [series_id]
#     output : consumption
#     type : regression
#   train :
#     data : cold_start_test
#     skip : [series_id]
#     output : consumption
#     type : regression
#   predict :
#     data : submission

de-normalize :
  data : submission
  normalized-data : cold_start_test
  target : consumption
  group-on : series_id

transfer:
  from :
    data : submission
    key : [series_id, timestamp]
    col : consumption
  to :
    data : submission_format
    key : [series_id, timestamp]
    col : consumption

csv-2 :
  data :
    - submission
    - submission_format

# copy-data-2:
#   from : cold_start_test
#   to : cold_start_test_daily

# customize-column :
#   - data : cold_start_test_daily
#     func : get_date_from_timestamp
#     in-col : timestamp
 
# group-by :
#   - data : cold_start_test
#     group-on :
#       - timestamp
#     aggregation:
#       - consumption : sum
#       - temperature : mean